package com.wbrawner.trainterval.shared.theme

import androidx.compose.ui.graphics.Color

val FadedRed = Color(0xFFFF06292)
val FadedGreen = Color(0xFF81C784)
val FadedYellow = Color(0xFFFFF176)
val FadedBlue = Color(0xFF64B5F6)


val md_theme_light_primary = Color(0xFF695F00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF9E534)
val md_theme_light_onPrimaryContainer = Color(0xFF201C00)
val md_theme_light_secondary = Color(0xFF8B5000)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDCBE)
val md_theme_light_onSecondaryContainer = Color(0xFF2C1600)
val md_theme_light_tertiary = Color(0xFFB02F00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDBD1)
val md_theme_light_onTertiaryContainer = Color(0xFF3B0900)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1C1D00)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1C1D00)
val md_theme_light_surfaceVariant = Color(0xFFE8E2D0)
val md_theme_light_onSurfaceVariant = Color(0xFF4A473A)
val md_theme_light_outline = Color(0xFF7B7768)
val md_theme_light_inverseOnSurface = Color(0xFFF5F77E)
val md_theme_light_inverseSurface = Color(0xFF313300)
val md_theme_light_inversePrimary = Color(0xFFDBC90A)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF695F00)
val md_theme_light_outlineVariant = Color(0xFFCBC6B5)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFDBC90A)
val md_theme_dark_onPrimary = Color(0xFF363100)
val md_theme_dark_primaryContainer = Color(0xFF4F4800)
val md_theme_dark_onPrimaryContainer = Color(0xFFF9E534)
val md_theme_dark_secondary = Color(0xFFFFB870)
val md_theme_dark_onSecondary = Color(0xFF4A2800)
val md_theme_dark_secondaryContainer = Color(0xFF693C00)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDCBE)
val md_theme_dark_tertiary = Color(0xFFFFB5A0)
val md_theme_dark_onTertiary = Color(0xFF5F1500)
val md_theme_dark_tertiaryContainer = Color(0xFF862200)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBD1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1C1D00)
val md_theme_dark_onBackground = Color(0xFFE6E971)
val md_theme_dark_surface = Color(0xFF1C1D00)
val md_theme_dark_onSurface = Color(0xFFE6E971)
val md_theme_dark_surfaceVariant = Color(0xFF4A473A)
val md_theme_dark_onSurfaceVariant = Color(0xFFCBC6B5)
val md_theme_dark_outline = Color(0xFF959181)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1D00)
val md_theme_dark_inverseSurface = Color(0xFFE6E971)
val md_theme_dark_inversePrimary = Color(0xFF695F00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFDBC90A)
val md_theme_dark_outlineVariant = Color(0xFF4A473A)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFFEB3B)
